packages:
  - 'core/**'
  - 'packages/**'
  - 'packages/*/**'
  - 'packages/@cradle-selrena/**'
  - 'assets/**'
  - 'scripts/**'
allowBuilds:
  '@bufbuild/buf': true
  better-sqlite3: true
  electron: true
  esbuild: true
  zeromq: true

shared-workspace-settings:
  install: true
