packages:
  - 'core/**'
  - 'protocol'
  - 'extensions/internal/sdk'
  - 'extensions/internal/template'
  - 'extensions/adapters/napcat-adapter'
  - 'extensions/adapters/vtube-studio-adapter'

allowBuilds:
  '@bufbuild/buf': true
  better-sqlite3: true
  electron: true
  esbuild: true
  zeromq: true

shared-workspace-settings:
  install: true
