# 【推荐】使用 .env 文件管理环境变量（参见 .env.example）
# 只有在无法使用环境变量或需要复杂对象配置时，才修改此文件。
# 此文件中的配置会被环境变量覆盖。

providers:
  qwen:
    api_key: "sk-..."
  deepseek:
    api_key: "sk-..."
  openai:
    api_key: "sk-..."

napcat:
  account: 123456789
  password: "password"
  token: "token"

vts_token: "vts-token"


database:
  password: ...
